/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practica1EVAL.gui;

import Practica1EVAL.dto.Carreras;
import Practica1EVAL.dto.Corredor;
import Practica1EVAL.logica.LogicaNegocio;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;

public class JDialogCronometro extends javax.swing.JFrame implements Runnable{
    
    private PantallaPrincipal pantallaprincipal;
    Thread t;
    int hcnt=0,mcnt=0,scnt=0,mscnt=0;
    String str="",nstr="",mstr="",dstr="";
    int cnt=0, cnt2=0;
    
  
    

    /**
     * Creates new form stopwatch
     */
    public JDialogCronometro() {
        initComponents();
        t=new Thread(this);
        reset();
        refrescarTablaTiempos();
      
        
    }

    
     private void refrescarTablaTiempos()
    {
    
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Dorsal","DNI","Carrera","Marca",});
        
        List<Corredor> listaCorredores = LogicaNegocio.getListaCorredores();
        
        for(Corredor corredor : listaCorredores)
        {
        
            dtm.addRow(corredor.toArrayStringTiempo());
        
        }
        
        jTableTiempos.setModel(dtm);
    
    }
  
  
 public void reset(){
     hcnt=0;mcnt=0;scnt=0;mscnt=0;cnt2=0;
     nstr="00:00:00";mstr="000";dstr="";
     display();
     
 }
 public void display(){
     lblDisp1.setText(nstr);
     lblDisp2.setText(mstr);
 }
 public void setTimeCounter(){
     nstr="";
     if(hcnt<10){
         nstr="0"+hcnt;
         
     }
     else{
         nstr=""+hcnt;
     }
       if(mcnt<10){
         nstr+=":0"+mcnt;
         
     }
     else{
         nstr+=":"+mcnt;
     } 
        if(scnt<10){
         nstr+=":0"+scnt;
         
     }
     else{
         nstr+=":"+scnt;
     } 
 }
 public void setMTimeCounter(){
    mstr=""; 
         if(mscnt<10){
         mstr="00"+mscnt;
         
     }
         else if(mscnt>=10 &&  mscnt< 100){
         mstr="0"+mscnt;
     } 
         else{
             mstr=""+mscnt;
            
         }
   
}
 public void run(){
    try {
        while(true){
              mscnt++; 
            if(mscnt>999){
                mscnt= 0;
                scnt++;
            }
            if(scnt>59) 
            {
                scnt = 0;
                mcnt++;
            }
            if(mcnt>60)
            {
                mcnt= 0;
                hcnt++;
            }
             if(hcnt>99)
            {
                reset();
            }
            setTimeCounter();
            setMTimeCounter();
            display();
            Thread.sleep(1);    
        }
   }
    catch (Exception e){
        
    }
}
 public void printToList(){
     cnt2++;
     dstr+="\n"+cnt2+") "+lblDisp1.getText()+" "+lblDisp2.getText()+"\n";
      

 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDisp1 = new javax.swing.JLabel();
        lblDisp2 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jButtonVuelta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTiempos = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDisp1.setFont(new java.awt.Font("Liberation Serif", 3, 70)); // NOI18N
        lblDisp1.setText("00:00:00");

        lblDisp2.setFont(new java.awt.Font("Digital-7 Mono", 3, 48)); // NOI18N
        lblDisp2.setText("000");

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jButtonStop.setText("Stop");
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });

        jButtonVuelta.setText("Vuelta");
        jButtonVuelta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVueltaActionPerformed(evt);
            }
        });

        jTableTiempos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableTiempos);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("MS PGothic", 3, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Inicia el cronómetro y selecciona un corredor en la tabla, \nel botón vuelta guardará el tiempo asociado al determinado corredor.");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonStop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStart, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonVuelta, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDisp1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDisp2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 245, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDisp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDisp2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnReset))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStop)
                    .addComponent(jButtonVuelta))
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

            if(btnStart.getText().equals("Start")){
           cnt++;
           if(cnt==1){ 
               t.start();
           }
           else{
               t.resume();
           }
       }
       
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
        t.suspend();
      
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        t.suspend();
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jButtonVueltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVueltaActionPerformed
       try 
       {
        int selectedCorredorTiempo = jTableTiempos.convertRowIndexToModel(jTableTiempos.getSelectedRow());
       
         Corredor corredor ;
       String editMarca =lblDisp1.getText()+lblDisp2.getText();
       
       List<Corredor> listaCorredoresTiempo = LogicaNegocio.getListaCorredores();
        corredor = listaCorredoresTiempo.get(selectedCorredorTiempo);
        corredor.setMarca(editMarca);
        refrescarTablaTiempos();  
      
       } catch (ArrayIndexOutOfBoundsException e)
       {
           System.out.print("No hay ningun corredor seleccionado al que asignar un tiempo");
       }
      
       
       
    }//GEN-LAST:event_jButtonVueltaActionPerformed

    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDialogCronometro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JButton jButtonVuelta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTiempos;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblDisp1;
    private javax.swing.JLabel lblDisp2;
    // End of variables declaration//GEN-END:variables
}
