/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practica1EVAL.gui;

import Practica1EVAL.dto.Carreras;
import Practica1EVAL.dto.Corredor;
import Practica1EVAL.logica.LogicaNegocio;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Requejo
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        refrescarTablaCorredores();
        refrescarTablaCarreras();
         jButtonAceptarCorredor.setEnabled(false);
         jButtonAceptar.setEnabled(false);
         filaSeleccionada.setVisible(false);
         filaSeleccionadaCorredor.setVisible(false);
       
        
    }
    
    private void refrescarTablaCorredores()
    {
    
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Nombre","DNI","Fecha Nacimiento","Direccion","Telf. Contacto","Dorsal","Carrera","Marca","Equipo"});
        
        List<Corredor> listaCorredores = LogicaNegocio.getListaCorredores();
        
        for(Corredor corredor : listaCorredores)
        {
        
            dtm.addRow(corredor.toArrayString());
        
        }
        
        jTableCorredores.setModel(dtm);
    
    }
    
    private void refrescarTablaCarreras()
    {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Nombre","Fecha","Lugar","NºParticpantes"});
        
         List<Carreras> listaCarreras = LogicaNegocio.getListaCarreras();
        
        for (Carreras carrera: listaCarreras)
            
            dtm.addRow(carrera.toArrayString());
        
        jTableCarreras.setModel(dtm);
    }
    
   
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPaneCorredores = new javax.swing.JScrollPane();
        jTableCorredores = new javax.swing.JTable();
        jScrollPaneCarreras = new javax.swing.JScrollPane();
        jTableCarreras = new javax.swing.JTable();
        jButtonEliminarCorredor = new javax.swing.JButton();
        jButtonEliminarCarrera = new javax.swing.JButton();
        editCarreraNombre = new javax.swing.JTextField();
        editCarreraLugar = new javax.swing.JTextField();
        editCarreraParticipantes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonEditarCarrera = new javax.swing.JButton();
        editCarreraFecha = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        filaSeleccionada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        editarCorredorNombre = new javax.swing.JTextField();
        editarCorredorDNI = new javax.swing.JTextField();
        editarCorredorFecha = new javax.swing.JTextField();
        editarCorredorDireccion = new javax.swing.JTextField();
        editarCorredorTelefono = new javax.swing.JTextField();
        editarCorredorDorsal = new javax.swing.JTextField();
        editarCorredorCarrera = new javax.swing.JTextField();
        jButtonAceptarCorredor = new javax.swing.JButton();
        filaSeleccionadaCorredor = new javax.swing.JTextField();
        jButtonEditarCorredor = new javax.swing.JButton();
        jLabelEditarEquipo = new javax.swing.JLabel();
        editarCorredorEquipo = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCarrera = new javax.swing.JMenu();
        jMenuItemAddCarrera = new javax.swing.JMenuItem();
        jMenuPrincipal = new javax.swing.JMenu();
        jMenuItemAddCorredor = new javax.swing.JMenuItem();
        jMenuCrono = new javax.swing.JMenu();
        jMenuCronometro = new javax.swing.JMenuItem();
        jMenuEquipos = new javax.swing.JMenu();
        jMenuItemEquipo = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableCorredores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneCorredores.setViewportView(jTableCorredores);

        jTableCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCarreras.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPaneCarreras.setViewportView(jTableCarreras);

        jButtonEliminarCorredor.setText("Eliminar");
        jButtonEliminarCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarCorredorActionPerformed(evt);
            }
        });

        jButtonEliminarCarrera.setText("Eliminar");
        jButtonEliminarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarCarreraActionPerformed(evt);
            }
        });

        editCarreraNombre.setEditable(false);

        editCarreraLugar.setEditable(false);

        editCarreraParticipantes.setEditable(false);

        jLabel1.setText("Nombre");

        jLabel2.setText("Participantes");

        jLabel3.setText("Lugar");

        jLabel4.setText("Fecha");

        jButtonEditarCarrera.setText("Editar");
        jButtonEditarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarCarreraActionPerformed(evt);
            }
        });

        editCarreraFecha.setEditable(false);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        filaSeleccionada.setEditable(false);

        jLabel5.setText("Nombre");

        jLabel6.setText("DNI");

        jLabel7.setText("FechaNac");

        jLabel8.setText("Direccion");

        jLabel9.setText("Telefono");

        jLabel10.setText("Dorsal");

        jLabel11.setText("Carrera");

        editarCorredorNombre.setEditable(false);

        editarCorredorDNI.setEditable(false);

        editarCorredorFecha.setEditable(false);

        editarCorredorDireccion.setEditable(false);

        editarCorredorTelefono.setEditable(false);

        editarCorredorDorsal.setEditable(false);

        editarCorredorCarrera.setEditable(false);

        jButtonAceptarCorredor.setText("Aceptar");
        jButtonAceptarCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarCorredorActionPerformed(evt);
            }
        });

        filaSeleccionadaCorredor.setEditable(false);

        jButtonEditarCorredor.setText("Editar");
        jButtonEditarCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarCorredorActionPerformed(evt);
            }
        });

        jLabelEditarEquipo.setText("Equipo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPaneCorredores, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPaneCarreras)
                                .addGap(40, 40, 40)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEliminarCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEliminarCorredor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEditarCorredor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEditarCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editCarreraNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editCarreraParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editCarreraLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editCarreraFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(editarCorredorDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addComponent(editarCorredorNombre))
                    .addComponent(editarCorredorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(editarCorredorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelEditarEquipo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(editarCorredorDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel11))
                    .addComponent(editarCorredorDorsal, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonAceptarCorredor)
                        .addGap(18, 18, 18)
                        .addComponent(filaSeleccionadaCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(editarCorredorCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(editarCorredorEquipo))
                .addGap(269, 269, 269))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonEditarCarrera)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarCarrera)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCarreraNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(editCarreraLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(filaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(editCarreraParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCarreraFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneCorredores, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditarCorredor)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarCorredor)))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarCorredorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(editarCorredorDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5)
                    .addComponent(editarCorredorCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(editarCorredorDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarCorredorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEditarEquipo)
                    .addComponent(editarCorredorEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(editarCorredorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarCorredorDorsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAceptarCorredor)
                    .addComponent(filaSeleccionadaCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jMenuCarrera.setText("Carreras");

        jMenuItemAddCarrera.setText("Añadir...");
        jMenuItemAddCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddCarreraActionPerformed(evt);
            }
        });
        jMenuCarrera.add(jMenuItemAddCarrera);

        jMenuBar1.add(jMenuCarrera);

        jMenuPrincipal.setText("Corredor");

        jMenuItemAddCorredor.setText("Añadir...");
        jMenuItemAddCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddCorredorActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jMenuItemAddCorredor);

        jMenuBar1.add(jMenuPrincipal);

        jMenuCrono.setText("Cronometro");

        jMenuCronometro.setText("Cronometro");
        jMenuCronometro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCronometroActionPerformed(evt);
            }
        });
        jMenuCrono.add(jMenuCronometro);

        jMenuBar1.add(jMenuCrono);

        jMenuEquipos.setText("Equipos");

        jMenuItemEquipo.setText("Equipos");
        jMenuItemEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEquipoActionPerformed(evt);
            }
        });
        jMenuEquipos.add(jMenuItemEquipo);

        jMenuBar1.add(jMenuEquipos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(213, 213, 213))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAddCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddCorredorActionPerformed
        
        JDialogAddCorredor dialogoCorredor = new JDialogAddCorredor(this, true);
        
        dialogoCorredor.setVisible(true);
        refrescarTablaCorredores();
        
    }//GEN-LAST:event_jMenuItemAddCorredorActionPerformed

    private void jMenuItemAddCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddCarreraActionPerformed
         JDialogAddCarrera dialogoCarrera = new JDialogAddCarrera(this, true);
        
        dialogoCarrera.setVisible(true);
        refrescarTablaCarreras();
    }//GEN-LAST:event_jMenuItemAddCarreraActionPerformed

    private void jButtonEliminarCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarCorredorActionPerformed

          int selectedCorredor = jTableCorredores.convertRowIndexToModel(jTableCorredores.getSelectedRow());
          LogicaNegocio.getListaCorredores().remove(selectedCorredor);
        
          refrescarTablaCorredores();
    }//GEN-LAST:event_jButtonEliminarCorredorActionPerformed

    private void jButtonEliminarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarCarreraActionPerformed
        int selectedCarrera = jTableCarreras.convertRowIndexToModel(jTableCarreras.getSelectedRow());
          LogicaNegocio.getListaCarreras().remove(selectedCarrera);
        
          refrescarTablaCarreras();
    }//GEN-LAST:event_jButtonEliminarCarreraActionPerformed

    private void jButtonEditarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarCarreraActionPerformed
        jButtonAceptar.setEnabled(true);
           int selectedCarrera = jTableCarreras.convertRowIndexToModel(jTableCarreras.getSelectedRow());
         
           editCarreraNombre.setText(jTableCarreras.getValueAt(selectedCarrera, 0).toString());
           editCarreraFecha.setText(jTableCarreras.getValueAt(selectedCarrera, 1).toString());
           editCarreraLugar.setText(jTableCarreras.getValueAt(selectedCarrera, 2).toString());
           editCarreraParticipantes.setText(jTableCarreras.getValueAt(selectedCarrera, 3).toString());
           filaSeleccionada.setText(Integer.toString(selectedCarrera));
           
          editCarreraNombre.setEditable(true);
          editCarreraLugar.setEditable(true);
          editCarreraParticipantes.setEditable(true);
          editCarreraFecha.setEditable(true);
          refrescarTablaCarreras(); 
          refrescarTablaCorredores();
          
    
    
    }//GEN-LAST:event_jButtonEditarCarreraActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
         String nombreEdit = editCarreraNombre.getText();
         String posicion = filaSeleccionada.getText();
         String lugarEdit = editCarreraLugar.getText();
         String fechaEdit = editCarreraFecha.getText();
         String participantesEdit = editCarreraParticipantes.getText();
         SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
         Date fechaDate = null;
        try {
            fechaDate = sdf.parse(fechaEdit);
        } 
        catch (ParseException ex) 
        {
            System.out.println(ex);
        }
        Carreras carrera = new Carreras(nombreEdit, fechaDate, lugarEdit, participantesEdit);
        
        LogicaNegocio.addCarrera(carrera);

        int j = Integer.parseInt(posicion);
        LogicaNegocio.getListaCarreras().remove(j);
           
          refrescarTablaCarreras();
          refrescarTablaCorredores();
          
           editCarreraNombre.setText("");
           editCarreraFecha.setText("");
           editCarreraLugar.setText("");
           editCarreraParticipantes.setText("");
           filaSeleccionada.setText("");
           
           editCarreraNombre.setEditable(false);
          editCarreraLugar.setEditable(false);
          editCarreraParticipantes.setEditable(false);
          editCarreraFecha.setEditable(false);
           jButtonAceptar.setEnabled(false);
   
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonAceptarCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarCorredorActionPerformed
         String posicion = filaSeleccionadaCorredor.getText();   
         String nombreEdit = editarCorredorNombre.getText(); 
         String DNIedit = editarCorredorDNI.getText();  
         String fechaEdit = editarCorredorFecha.getText();
         String direccionEdit = editarCorredorDireccion.getText();
         String telefonoEdit = editarCorredorTelefono.getText();
         String DorsalEdit = editarCorredorDorsal.getText();
         String carreraEdit = editarCorredorCarrera.getText();
         //añado el String para modificar el campo editarEquipo
         String equipoEdit = editarCorredorEquipo.getText();
                 
         SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
         Date fechaDate = null;
         String marcaEdit ="";
         int dorsal= Integer.parseInt(DorsalEdit);
        try {
            fechaDate = sdf.parse(fechaEdit);
        } 
        catch (ParseException ex) 
        {
            System.out.println(ex);
        }
        
        //añado el equipo al constructor
        Corredor corredor = new Corredor(nombreEdit, DNIedit, fechaDate, direccionEdit, telefonoEdit, dorsal, carreraEdit, marcaEdit, equipoEdit);       
        LogicaNegocio.addCorredor(corredor);
        int j = Integer.parseInt(posicion);
        LogicaNegocio.getListaCorredores().remove(j);
        jButtonAceptarCorredor.setEnabled(false);
  
         
         refrescarTablaCorredores();
         refrescarTablaCarreras();
          editarCorredorNombre.setText("");
          editarCorredorDNI.setText("");
          editarCorredorFecha.setText("");
          editarCorredorDireccion.setText("");
          editarCorredorTelefono.setText("");
          editarCorredorDorsal.setText("");
          editarCorredorCarrera.setText("");
          //dejo vacio el campo editar equipo para que no haya problemas y quede bien
          editarCorredorEquipo.setText("");
          filaSeleccionadaCorredor.setText("");
          
          editarCorredorCarrera.setEditable(false);
          editarCorredorDNI.setEditable(false);
          editarCorredorDireccion.setEditable(false);
          editarCorredorDorsal.setEditable(false);
          editarCorredorTelefono.setEditable(false);
          editarCorredorFecha.setEditable(false);
          editarCorredorNombre.setEditable(false);
          //dejo sin poder editarse el campo equipo para que si no esta seleccionado ninguno no de problemas
          editarCorredorEquipo.setEditable(false);
          
    }//GEN-LAST:event_jButtonAceptarCorredorActionPerformed

    private void jButtonEditarCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarCorredorActionPerformed
         jButtonAceptarCorredor.setEnabled(true);
        int selectedCorredor = jTableCorredores.convertRowIndexToModel(jTableCorredores.getSelectedRow());
           
          editarCorredorNombre.setText(jTableCorredores.getValueAt(selectedCorredor, 0).toString());
          editarCorredorDNI.setText(jTableCorredores.getValueAt(selectedCorredor, 1).toString());
          editarCorredorFecha.setText(jTableCorredores.getValueAt(selectedCorredor, 2).toString());
          editarCorredorDireccion.setText(jTableCorredores.getValueAt(selectedCorredor, 3).toString());
          editarCorredorTelefono.setText(jTableCorredores.getValueAt(selectedCorredor, 4).toString());
          editarCorredorDorsal.setText(jTableCorredores.getValueAt(selectedCorredor, 5).toString());
          editarCorredorCarrera.setText(jTableCorredores.getValueAt(selectedCorredor, 6).toString());
          //le pongo al campo editarEquipo los datos que tiene ese corredor
          editarCorredorEquipo.setText(jTableCorredores.getValueAt(selectedCorredor, 8).toString());
        
         filaSeleccionadaCorredor.setText(Integer.toString(selectedCorredor));
   
          
          
          refrescarTablaCorredores(); 
          refrescarTablaCarreras();
          
          editarCorredorCarrera.setEditable(true);
          editarCorredorDNI.setEditable(true);
          editarCorredorDireccion.setEditable(true);
          editarCorredorDorsal.setEditable(true);
          editarCorredorTelefono.setEditable(true);
          editarCorredorFecha.setEditable(true);
          editarCorredorNombre.setEditable(true);
          //añado que se pueda editar el campoEquipo
           editarCorredorEquipo.setEditable(true);
          
          
 
    }//GEN-LAST:event_jButtonEditarCorredorActionPerformed

    private void jMenuCronometroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCronometroActionPerformed
     
        JDialogCronometro dialogoCrono = new JDialogCronometro ();
        dialogoCrono.setVisible(true);
        
    }//GEN-LAST:event_jMenuCronometroActionPerformed

    
    //añadimos el menu para ir a los equipos
    private void jMenuItemEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEquipoActionPerformed
        
       JDialogEquipos dialogoEquipo = new JDialogEquipos(this, true);
       dialogoEquipo.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemEquipoActionPerformed

        
                                                
    /**
     * 
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField editCarreraFecha;
    private javax.swing.JTextField editCarreraLugar;
    private javax.swing.JTextField editCarreraNombre;
    private javax.swing.JTextField editCarreraParticipantes;
    private javax.swing.JTextField editarCorredorCarrera;
    private javax.swing.JTextField editarCorredorDNI;
    private javax.swing.JTextField editarCorredorDireccion;
    private javax.swing.JTextField editarCorredorDorsal;
    private javax.swing.JTextField editarCorredorEquipo;
    private javax.swing.JTextField editarCorredorFecha;
    private javax.swing.JTextField editarCorredorNombre;
    private javax.swing.JTextField editarCorredorTelefono;
    private javax.swing.JTextField filaSeleccionada;
    private javax.swing.JTextField filaSeleccionadaCorredor;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAceptarCorredor;
    private javax.swing.JButton jButtonEditarCarrera;
    private javax.swing.JButton jButtonEditarCorredor;
    private javax.swing.JButton jButtonEliminarCarrera;
    private javax.swing.JButton jButtonEliminarCorredor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEditarEquipo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuCarrera;
    private javax.swing.JMenu jMenuCrono;
    private javax.swing.JMenuItem jMenuCronometro;
    private javax.swing.JMenu jMenuEquipos;
    private javax.swing.JMenuItem jMenuItemAddCarrera;
    private javax.swing.JMenuItem jMenuItemAddCorredor;
    private javax.swing.JMenuItem jMenuItemEquipo;
    private javax.swing.JMenu jMenuPrincipal;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneCarreras;
    private javax.swing.JScrollPane jScrollPaneCorredores;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTableCarreras;
    private javax.swing.JTable jTableCorredores;
    // End of variables declaration//GEN-END:variables
}
